version: '3.7'
services:
  api:
    image: openjdk:8
    container_name: api
    stdin_open: true
    volumes:
      - .:/app
      - gradle_cache:/root/.gradle
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      DB_HOST: db
      DB_PORT: 27017
      DB_USER: api_user
      DB_PASSWORD: api_password
    depends_on:
      - db
    working_dir: /app
    command: ["/app/gradlew", "bootRun"]
  db:
    image: mongo:4.0
    container_name: mongo
    environment:
      MONGO_DATA_DIR: /var/lib/mongo/data/tcp_data
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_ROOT_USERNAME: api_user
      MONGO_INITDB_ROOT_PASSWORD: api_password
    volumes:
      - mongo_db:/var/lib/mongo/data/tcp_data
    ports:
      - "27017:27017"
volumes:
  mongo_db:
  gradle_cache: