server.port: 8080
management:
  endpoints:
    web.base-path: /
    web.exposure.include: "*"
    enabled-by-default: true
  endpoint:
    health.enabled: true
    health.show-details: always

spring.data.mongodb:
  authentication-database: admin
  database: tcp
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  host: ${DB_HOST}
  port: ${DB_PORT}
